//
//  ClockViewController.swift
//  Lucid Weather Clock
//
//  Created by Wojciech Rutkowski on 04/10/2016.
//  Copyright (c) 2016 Wojciech Rutkowski. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ClockViewControllerInput {
    func displaySomething(viewModel: ClockViewModel)
}

protocol ClockViewControllerOutput {
    func doSomething(request: ClockRequest)
}

class ClockViewController: UIViewController, ClockViewControllerInput {
    var output: ClockViewControllerOutput!
    var router: ClockRouter!

    // MARK: Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        ClockConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        doSomethingOnLoad()
    }

    // MARK: Event handling

    func doSomethingOnLoad() {
        // NOTE: Ask the Interactor to do some work

        let request = ClockRequest()
        output.doSomething(request: request)
    }

    // MARK: Display logic

    func displaySomething(viewModel: ClockViewModel) {
        // NOTE: Display the result from the Presenter

        // nameTextField.text = viewModel.name
    }
}
